---

services:
  ldap:
    image: ghcr.io/surfscz/sram-ldap:main
    ports:
      - 1389:1389
    environment:
      LDAP_ROOT: "${BASEDN}"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "changethispassword"
      LDAP_CONFIG_ADMIN_USERNAME: "admin"
      LDAP_CONFIG_ADMIN_PASSWORD: "changethispassword"
      LDAP_CONFIG_ADMIN_ENABLED: "yes"
      LDAP_CUSTOM_SCHEMA_DIR: "/opt/ldap/schema"
      LDAP_SKIP_DEFAULT_TREE: "yes"
      LDAP_ENABLE_TLS: "no"
      LDAP_ENABLE_SYNCPROV: "yes"
    volumes:
      - ./schema:/opt/ldap/schema
      - ./ldif:/opt/ldap/ldif
      - ./backup.ldif:/backup.ldif:ro