name: CI

on: [push]

jobs:
  plsc-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - '3.8'

    services:
      ldap:
        image: bitnami/openldap
        ports:
          - 1389:1389
        env:
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: secret
          LDAP_ROOT: dc=sram,dc=tld
          LDAP_PORT_NUMBER: 1389

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsasl2-dev libldap2-dev

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Load ldap - check connection
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapwhoami -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret||sleep 5)"

    - name: Load ldap - cleanup ldap
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "/opt/bitnami/openldap/bin/ldapdelete -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -r ou=users,dc=sram,dc=tld"

    - name: Load ldap - load ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "for f in eduPerson sczGroup voPerson sram sram_services; do /opt/bitnami/openldap/bin/ldapadd -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/$f.ldif; done"

    - name: Load ldap - check structure
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "/opt/bitnami/openldap/bin/ldapsearch -H ldap://ldap:1389 -b dc=sram,dc=tld -D cn=admin,dc=sram,dc=tld -w secret"
    
    # Setup tmate session
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3

    - name: Run pytest
      run: python3 pytest tests
      env:
        LDAP_URL: ldap://localhost:1389
        LDAP_ADMIN_PASSWORD: secret
        LDAP_BASE_DN: dc=sram,dc=tld
        LDAP_BIND_DN: cn=admin,dc=sram,dc=tld
        SBS_HOST: http://localhost:3080
        SBS_PASSWORD: secret

    - name: Search ldap - show results !
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "/opt/bitnami/openldap/bin/ldapsearch -H ldap://ldap:1389 -b dc=sram,dc=tld -D cn=admin,dc=sram,dc=tld -w secret"


