name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6]

    services:
      ldap:
        image: bitnami/openldap
        env:
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: secret
          LDAP_ROOT: dc=sram,dc=tld
          LDAP_PORT_NUMBER: 1389

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libsasl2-dev libldap2-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Load ldap - test
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapwhoami -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret||sleep 5)

    - name: Load ldap - ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapadd -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/eduPerson.ldif)"

    - name: Load ldap - ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapadd -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/voPerson.ldif)"

    - name: Load ldap - ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapadd -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/sczGroup.ldif)"

    - name: Load ldap - ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapadd -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/sram.ldif)"

    - name: Load ldap - ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapadd -H ldap://ldap:1389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/sram_services.ldif)"

    - name: Test with pytest
      run: |
        echo pytest