name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6]

    services:
      ldap:
        image: bitnami/openldap
        ports:
          - 3389:3389
        env:
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: adminpassword
          LDAP_ROOT: dc=example,dc=com
          LDAP_PORT_NUMBER: 3389

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libsasl2-dev libldap2-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Load ldap - test
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapwhoami -h localhost:3389 -D cn=admin,dc=example,dc=com -w adminpassword||sleep 5)

    - name: Load ldap - ldif
      uses: docker://bitnami/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(/opt/bitnami/openldap/bin/ldapadd -h ldap:3389 -D cn=admin,dc=example,dc=com -w adminpassword -f etc/ldif/sram.ldif)"

    - name: Test with pytest
      run: |
        echo pytest