name: CI

on: [push]

jobs:
  plsc-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - '3.8'

    services:
      ldap:
        image: osixia/openldap:latest
        ports:
          - 389:389
        env:
          LDAP_DOMAIN: sram.tld 
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: secret
          LDAP_CONFIG_PASSWORD: config
          LDAP_TLS: true

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsasl2-dev libldap2-dev

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Load ldap - check connection
      uses: docker://osixia/openldap
      with:
        entrypoint: /bin/bash
        args: -c "(ldapwhoami -H ldap://localhost:389 -D cn=admin,dc=sram,dc=tld -w secret||sleep 5)"

    - name: Load ldap - cleanup ldap
      uses: docker://osixia/openldap
      with:
        entrypoint: /bin/bash
        args: -c "ldapdelete -H ldap://localhost:389 -D cn=admin,dc=sram,dc=tld -w secret -r ou=users,dc=sram,dc=tld"

    - name: Load ldap - config objectclasses ldif
      uses: docker://osixia/openldap
      with:
        entrypoint: /bin/bash
        args: -c "for f in eduPerson voPerson groupOfMembers; do ldapadd -H ldap://localhost:389 -D cn=admin,cn=config -w config -f etc/ldif/$f.ldif; done"

    - name: Load ldap - loaad SRAM root ldif
      uses: docker://osixia/openldap
      with:
        entrypoint: /bin/bash
        args: -c "for f in sram sram_services; do ldapadd -H ldap://localhost:389 -D cn=admin,dc=sram,dc=tld -w secret -f etc/ldif/$f.ldif; done"

    - name: Load ldap - check structure
      uses: docker://osixia/openldap
      with:
        entrypoint: /bin/bash
        args: -c "ldapsearch -H ldap://localhost:389 -b dc=sram,dc=tld -D cn=admin,dc=sram,dc=tld -w secret"
    
    # Setup tmate session
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3

    - name: Run pytest
      run: 
        export PYTHONPATH="."
        pytest
      env:
        LDAP_URL: ldap://ldap:389
        LDAP_ADMIN_PASSWORD: secret
        LDAP_BASE_DN: dc=sram,dc=tld
        LDAP_BIND_DN: cn=admin,dc=sram,dc=tld
        
    - name: Search ldap - show results !
      uses: docker://osixia/openldap
      with:
        entrypoint: /bin/bash
        args: -c "ldapsearch -H ldap://localhost:389 -b dc=sram,dc=tld -D cn=admin,dc=sram,dc=tld -w secret"


